// eslint.config.mjs

import { dirname } from "path";
import { fileURLToPath } from "url";
import js from "@eslint/js";
import { FlatCompat } from "@eslint/eslintrc";

import tsParser from "@typescript-eslint/parser";
import reactPlugin from "eslint-plugin-react";
import reactHooksPlugin from "eslint-plugin-react-hooks";
import jsxA11yPlugin from "eslint-plugin-jsx-a11y";
import nextPlugin from "@next/eslint-plugin-next";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

const eslintConfig = [
  // Base Next.js + ESLint recommended configs
  ...compat.extends(
    "next/core-web-vitals",
    "next/typescript",
    "eslint:recommended",
    "prettier" // Add prettier config to disable conflicting rules
  ),

  // Rules & plugins for all code files
  {
    files: ["**/*.{js,jsx,ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      react: reactPlugin,
      "react-hooks": reactHooksPlugin,
      "jsx-a11y": jsxA11yPlugin,
      "@next/next": nextPlugin,
    },
    rules: {
      // Next.js plugin rules (recommended)
      ...nextPlugin.configs.recommended.rules,

      // React & hooks
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",

  // General JS / TS rules
  // Disable `no-undef` because TypeScript already checks for undefined variables
  // and it causes false positives for types like `React` and `NodeJS`.
  "no-undef": "off",
  "no-unused-vars": "off", // TS handles this
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "prefer-const": "error",
      "no-var": "error",
      "object-shorthand": "error",
      "prefer-template": "error",

      // Accessibility
      "jsx-a11y/alt-text": "error",
      "jsx-a11y/anchor-has-content": "error",
      "jsx-a11y/aria-role": "error",
    },
    settings: {
      react: {
        version: "detect",
      },
    },
  },

  // Ignore files / folders (do not ignore eslint.config.mjs)
  {
    ignores: [
  // Ignore next-env.d.ts since it uses a triple-slash reference generated by Next.js
  "next-env.d.ts",
      ".next/**/*",
      "node_modules/**/*",
      "out/**/*",
      "dist/**/*",
      "public/charting_library/**/*",
      "src/libs/charting_library/**/*",
      // Remove "*.config.mjs" or similar so that this config file is not ignored
    ],
  },
];

export default eslintConfig;
